apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profitable-orders-db-pvc
  namespace: profitable-orders-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual