apiVersion: v1
kind: Service
metadata:
  name: postgresdb-profitable-orders-service
  namespace: profitable-orders-ns
  labels:
    app: postgresdb-profitable-orders
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb-profitable-orders