apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitable-orders
  namespace: profitable-orders-ns
  labels:
    app: profitable-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profitable-orders
  template:
    metadata:
      labels:
        app: profitable-orders
    spec:
      nodeSelector:
        node: "ora4"
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: profitable-orders
          image: lesykm/market-app:latest
          command: ["java", "-jar", "/opt/app/profitable-orders-service.jar"]
          env:
            - name: STATIC_DATA_URL
              value: "http://static-data-service.static-data-ns:8084/"
            - name: MARKET_API_READER_URL
              value: "http://market-api-reader-service.market-api-reader-ns:8081/"
            - name: PROFITABLE_ORDERS_PORT
              value: "8085"
            - name: KAFKA_HOSTNAME
              value: "kafka-service.kafka-ns.svc.cluster.local"
            - name: KAFKA_PORT
              value: "9092"
            - name: DATABASE_HOSTNAME
              value: postgresdb-profitable-orders-service
            - name: DATABASE_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE_NAME
              value: market_data
            - name: ROOT_LOG_LEVEL
              value: INFO
            - name: APP_LOG_LEVEL
              value: INFO
            - name: SPRING_LOG_LEVEL
              value: INFO
            - name: KAFKA_CONSUMER_POOL_SIZE
              value: "5"
            - name: KAFKA_CONSUMER_QUEUE_SIZE
              value: "500"
            - name: KAFKA_CLEANER_CACHE_LIFETIME_MINUTES
              value: "5"
            - name: KAFKA_CLEANER_REGISTRY_READ_TIME_SECONDS
              value: "60"
            - name: KAFKA_CLEANER_SCHEDULER_DELAY
              value: "300000"
            - name: KAFKA_CLEANER_SCHEDULER_INITIAL_DELAY
              value: "5000"
            - name: KAFKA_CLEANER_ENABLED
              value: "true"
          ports:
            - name: app-port
              containerPort: 8085