apiVersion: v1
kind: Service
metadata:
  name: profitable-orders-service
  namespace: profitable-orders-ns
  labels:
    app: profitable-orders
spec:
  type: ClusterIP
  ports:
    - targetPort: 8085
      port: 8085
  selector:
    app: profitable-orders