apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-analyzer-db-pvc
  namespace: order-analyzer-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual