apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-analyzer-db-pv
spec:
  claimRef:
    name: order-analyzer-db-pvc
    namespace: order-analyzer-ns
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/projects/order-analyzer-db"