apiVersion: v1
kind: Service
metadata:
  name: postgresdb-order-analyzer-service
  namespace: order-analyzer-ns
  labels:
    app: postgresdb-order-analyzer
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb-order-analyzer