apiVersion: v1
kind: Service
metadata:
  name: order-analyzer-service
  namespace: order-analyzer-ns
  labels:
    app: order-analyzer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
      protocol: TCP
  selector:
    app: order-analyzer