apiVersion: v1
kind: Service
metadata:
  name: order-analyzer-service
  namespace: order-analyzer-ns
  labels:
    app: order-analyzer
spec:
  type: ClusterIP
  ports:
    - targetPort: 8082
      port: 8082
  selector:
    app: order-analyzer