apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-data-db-pv
spec:
  claimRef:
    name: static-data-db-pvc
    namespace: static-data-ns
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/projects/static-data-db"