apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data-db-pvc
  namespace: static-data-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual