apiVersion: v1
kind: Service
metadata:
  name: postgresdb-static-data-service
  namespace: static-data-ns
  labels:
    app: postgresdb-static-data
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb-static-data