apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sde-path-pvc
  namespace: static-data-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual