apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-db-pv
spec:
  claimRef:
    name: web-db-pvc
    namespace: web-ui-ns
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/projects/web-db"