apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-db-pvc
  namespace: web-ui-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual