version: '3'

services:
  postgresdb-order-analyzer:
    image: postgres:16
    container_name: postgresdb-order-analyzer
    ports:
      - 5432:5432
    volumes:
      - order_analyzer_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  order-analyzer-service:
    image: lesykm/market-app:latest
    container_name: order-analyzer-service
    ports:
      - 8082:8082
    depends_on:
      postgresdb-order-analyzer:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      ORDERS_ANALYZER_PORT: 8082
      DATABASE_HOSTNAME: postgresdb-order-analyzer
      DATABASE_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DATABASE_NAME: market_data
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 9092
      ROOT_LOG_LEVEL: INFO
      APP_LOG_LEVEL: INFO
      SPRING_LOG_LEVEL: INFO
      KAFKA_LOG_LEVEL: INFO
      KAFKA_CONSUMER_POOL_SIZE: 5
      KAFKA_CONSUMER_QUEUE_SIZE: 500
      KAFKA_CLEANER_CACHE_LIFETIME_MINUTES: 5
      KAFKA_CLEANER_REGISTRY_READ_TIME_SECONDS: 60
      KAFKA_CLEANER_SCHEDULER_DELAY: 300000
      KAFKA_CLEANER_SCHEDULER_INITIAL_DELAY: 900000
      KAFKA_PRODUCER_SCHEDULER_DELAY: 300000
      KAFKA_PRODUCER_SCHEDULER_INITIAL_DELAY: 5000
      KAFKA_CLEANER_ENABLED: true
      KAFKA_PRODUCER_POOL_SIZE: 5
volumes:
  order_analyzer_db: {}
