version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 22181:2181
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
  market-api-reader:
    image: lesykm/market-app:latest
    container_name: market-api-reader
    ports:
      - 8081:8081
    depends_on:
      kafka:
        condition: service_started
      static-data-service:
        condition: service_healthy
    environment:
      STATIC_DATA_URL: http://static-data-service:8084/
      MARKET_API_READER_PORT: 8081
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 9092
      ROOT_LOG_LEVEL: INFO
      APP_LOG_LEVEL: INFO
      SPRING_LOG_LEVEL: INFO
      KAFKA_PRODUCER_POOL_SIZE: 5
      KAFKA_PRODUCER_QUEUE_SIZE: 500
      KAFKA_PRODUCER_CACHE_LIFETIME_MINUTES: 5
      KAFKA_PRODUCER_SCHEDULER_DELAY: 300_000
      KAFKA_PRODUCER_SCHEDULER_INITIAL_DELAY: 5000
      KAFKA_PRODUCER_RUN_COUNT: -1