logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      mlesyk: ${APP_LOG_LEVEL:INFO}
      springframework: ${SPRING_LOG_LEVEL:INFO}
server:
  port : ${STATIC_DATA_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME:172.25.141.246}:${DATABASE_PORT:5432}/static_data
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL_ENABLED:false}
app:
  snakeyaml:
    maxYamlCodePoints: 1_000_000_000
  sde:
    file_name: sde.zip
    file_path: ${SDE_FILE_PATH:./}
    resources_url: https://developers.eveonline.com/docs/services/sde/
    checksum_name: sde-checksum
    type_id_filename: types.yaml
    market_groups_filename: marketGroups.yaml
    solar_systems_filename: solarsystem.yaml