apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: market-api-reader-ns
data:
  .dockerconfigjson: <replace with 'cat .docker/config | base64'>
type: kubernetes.io/dockerconfigjson